#!/bin/sh
# Copyright (C) 2023 Toradex AG.
# Licensed on MIT

composefs_enabled() {
	return 0
}

composefs_error() {
	fatal "$@"
}

composefs_run() {
	info "Running composefs script..."

	if [ -d "$ROOTFS_DIR" ]; then
		# When built with composefs support ostree-prepare-root will
		# look for objects under /sysroot which is actually the rootfs
		# directory in the ramdisk.
		ln -sf "$ROOTFS_DIR" /sysroot
	else
		debug "No rootfs has been set"
	fi
}
